### PR TITLE
Improve 3 tests and add pytest markers to skip the remaining tests

### PR DESCRIPTION
**Pull request by seav**
### Proposed changes in this pull request
This PR provides a baseline release for integrating the functional test suite into the **cadasta-platform** repository. Currently 3 tests that do not need any test fixtures are allowed to be run against the platform server.
- Update package version to 0.2.0.
- Add a **util.py** script which contains a `random_string()` method. This allows the generation of identifiers like usernames, project names, etc. that is extremely unlikely to conflict with any existing object in the database.
- Add helper find-element methods to the `CustomWebDriver` to reduce line lengths.
- Replace the existing `try`-`catch` explicit wait code in `CustomWebDriver` with the “more standard” explicit wait code that uses expected conditions and `By` locator tuples. (See [docs](http://selenium-python.readthedocs.io/waits.html#explicit-waits).)
- Improve 3 tests that correspond to the User Accounts test cases #R6, #R9, and #R12. These test cases do not need any test fixtures. The tests’ assertions were also improved to ensure that the `This field is required.` message is verified to appear on the exact input field. Previously, the tests only checked that this message appeared _anywhere_ on the page.
- Mark all of the remaining tests with the built-in pytest `skip` marker so that those tests aren’t run. (As tests are slowly included back into the test suite, these markers will be incrementally removed.)
- Improve the test assertion for 1 other test (`test_login_failure`) (even if it was marked as `skip`). Previously, this test checks that an alert message was displayed with an invalid login attempt. However, a successful login attempt _also_ shows an alert message (`Successfully signed in as <username>.`) which means that the test always passes. The test now checks for the specific alert message expected.

### When should this PR be merged
When convenient.

### Risks
None.

### Follow-up actions
Approve corresponding [PR on the **cadasta-platform** repository](https://github.com/Cadasta/cadasta-platform/pull/1722).

#### General

- [ ] **Is this PR explained thoroughly?** All code changes must be accounted for in the PR description. 
- [ ] **Is the PR labeled correctly?** It should have the `migration` label if a new migration is added. 
- [ ] **Is the risk level assessment sufficient?** The risks section should contain all risks that might be introduced with the PR and which actions we need to take to mitigate these risks. Possible risks are database migrations, new libraries that need to be installed or changes to deployment scripts.

#### Functionality

- [ ] **Are all requirements met?** Compare implemented functionality with the requirements specification.
- [ ] **Does the UI work as expected?** There should be no Javascript errors in the console; all resources should load. There should be no unexpected errors. Deliberately try to break the feature to find out if there are corner cases that are not handled. 

#### Code

- [ ] **Do you fully understand the introduced changes to the code?** If not ask for clarification, it might uncover ways to solve a problem in a more elegant and efficient way.
- [ ] **Does the PR introduce any inefficient database requests?** Use the debug server to check for duplicate requests. 
- [ ] **Are all necessary strings marked for translation?** All strings that are exposed to users via the UI must be [marked for translation](https://docs.djangoproject.com/en/1.10/topics/i18n/translation/). 

#### Tests

- [ ] **Are there sufficient test cases?** Ensure that all components are tested individually; models, forms, and serializers should be tested in isolation even if a test for a view covers these components. 
- [ ] **If this is a bug fix, are tests for the issue in place?**  There must be a test case for the bug to ensure the issue won’t regress. Make sure that the tests break without the new code to fix the issue.
- [ ] **If this is a new feature or a significant change to an existing feature?** has the manual testing spreadsheet been updated with instructions for manual testing?

#### Security

- [ ] **Confirm this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.**
- [ ] **Are all UI and API inputs run through forms or serializers?** 
- [ ] **Are all external inputs validated and sanitized appropriately?**
- [ ] **Does all branching logic have a default case?**
- [ ] **Does this solution handle outliers and edge cases gracefully?**
- [ ] **Are all external communications secured and restricted to SSL?**

#### Documentation

- [ ] **Are changes to the UI documented in the platform docs?** If this PR introduces new platform site functionality or changes existing ones, the changes must be documented in the [Cadasta Platform Documentation](https://github.com/Cadasta/cadasta-docs).
- [ ] **Are changes to the API documented in the API docs?** If this PR introduces new API functionality or changes existing ones, the changes must be documented in the [API docs](https://github.com/Cadasta/api-docs).
- [ ] **Are reusable components documented?** If this PR introduces components that are relevant to other developers (for instance a mixin for a view or a generic form) they should be documented in the Wiki.

### CODE REVIEW

**Comment by seav** [comment]
I wanted to experiment with using Selenium IDE, but it isn't supported with the latest version of Firefox (v55) (see this [Selenium blog post](https://seleniumhq.wordpress.com/2017/08/09/firefox-55-and-selenium-ide/)). I am not experienced enough with VirtualBox to try and create a VM so I can install a lower version of Firefox, but I can try. This means that I cannot assess whether our existing tests are compatible and editable using the IDE. Do you have any other suggestion I can try so I can run the Selenium IDE with a minimum of fuss?

**Comment by oliverroick** [comment]
From the link you posted:

> The first thing is that there are now a wealth of tools that are stepping up to fill the gap.

We should find these tools and figure out which are useful to us.

**Comment by seav** [comment]
I've done some research and testing on alternative tools and on Selenium IDE itself. Here are some highlights.

- I've read through a lot of Selenium IDE alternatives and you get a lot of tools, some cloud-based and some that you need to install. You can read more [here](https://news.ycombinator.com/item?id=13586904), [here](http://screenster.io/selenium-alternatives-for-testing-automation/), and [here](https://www.quora.com/What-are-some-great-alternatives-to-selenium-testing).
- Based on what I've seen, we generally have script-based tools (you write a script either in a high-level programming language or even something like MarkDown) or record-and-playback tools which you can then tweak afterwards.
- Most tools and services are built on top of Selenium because it is the de facto browser automation tool, but some use their own stack.
- Some of the user-friendly and nice tools are cloud-based, but we need to pay for them. ([TestCraft](https://www.testcraft.io/) and [Ghost Inspector](https://ghostinspector.com/) are two of the services that seem nice.)
- If we want to stick with the Python+Selenium toolset, unfortunately only Selenium IDE (and another, also now unsupported, Firefox extension called Selenium Builder) is available that can record and export to Python code. There is nothing like Selenium IDE on Chrome and one ongoing work to [re-implement Selenium IDE using the Web Extension framework](https://github.com/ddavison/selenium-ide) instead of XPI is far from finished.
- I was able to create a new VM and install XFCE + Firefox 54 + Selenium IDE and played around with it. It is actually pretty nifty and you can quickly create test cases by recording stuff and then exporting them as Python code. The drawbacks are the following:
    - It exports to Python 2, not Python 3. (This is a small matter.)
    - The code uses the unittest framework (`self.assertEqual`, etc.) instead of pytest.
    - The code is not PEP8 compliant (long lines) so you still need to clean the code up afterwards.
    - You can only export to Python one test case at a time. (Exporting a test suite is only supported for C#, Java, and Ruby.)

Given the points above, I think we can still create test cases quickly using the IDE and then cleaning up afterwards as opposed to hand-coding them from scratch. This might be a good approach especially for those test cases that involve a lot of clicking and typing. I guess a good analogy would be: when digitizing a printed piece of text, would you rather type it by hand, or use an OCR tool and then proofread and copy-edit it afterwards?

**Comment by seav** [comment]
Closing. Will open another PR that integrates BrowserStack.

**Pull request closed without merging**
